# .github/workflows/publish.yml
name: Publish to npm

on:
  push:
    tags:
      - 'v*'    # Publie lorsque le tag suit le modèle vX.X.X (par exemple, v1.0.0)

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to Yarn (optional)
        run: yarn publish --non-interactive --new-version "${{ github.ref_name }}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}